"""added user_id as foreign constraint

Revision ID: 02cf10cfd974
Revises: 45c7a944c641
Create Date: 2025-08-31 10:36:48.608221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02cf10cfd974'
down_revision: Union[str, Sequence[str], None] = '45c7a944c641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('thread_thread_id_fkey'), 'thread', type_='foreignkey')
    op.create_foreign_key(None, 'thread', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('thread', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.create_foreign_key(op.f('thread_thread_id_fkey'), 'thread', 'user', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_column('thread', 'user_id')
    # ### end Alembic commands ###