"""changes message to content

Revision ID: 06c4b5ed5e9c
Revises: 89128e2e0de3
Create Date: 2025-08-31 11:04:09.958600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c4b5ed5e9c'
down_revision: Union[str, Sequence[str], None] = '89128e2e0de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_messages', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('thread_messages', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('thread_messages', 'content')
    # ### end Alembic commands ###